USE [M_VPSA_V3]
GO

/****** Object:  StoredProcedure [dbo].[GENERACION_IMPORTE_BOLETA]    Script Date: 24/3/2023 21:53:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE
	OR

ALTER PROCEDURE [dbo].[GENERACION_IMPORTE_BOLETA]
AS
DECLARE @IdDetalleBoleta INT
DECLARE @ImporteFinal DECIMAL
DECLARE @ImporteBoleta DECIMAL = 0

DECLARE CURSOR_DETALLEBOLETA CURSOR
FOR
SELECT D.IdDetalleBoleta,
	I.ImporteFinal
FROM DETALLEBOLETA D
JOIN IMPUESTOINMOBILIARIO I ON I.IdImpuesto = D.IdImpuesto
WHERE D.IdBoleta = (
		SELECT IDENT_CURRENT('BOLETA')
		)

-- APERTURA DEL CURSOR
OPEN CURSOR_DETALLEBOLETA

FETCH NEXT
FROM CURSOR_DETALLEBOLETA
INTO @IdDetalleBoleta,
	@ImporteFinal;

WHILE @@FETCH_STATUS = 0
BEGIN
	UPDATE DETALLEBOLETA
	SET Importe = @ImporteFinal
	WHERE IdDetalleBoleta = @IdDetalleBoleta

	SET @ImporteBoleta = @ImporteBoleta + @ImporteFinal

	FETCH NEXT
	FROM CURSOR_DETALLEBOLETA
	INTO @IdDetalleBoleta,
		@ImporteFinal;
END

CLOSE CURSOR_DETALLEBOLETA

DEALLOCATE CURSOR_DETALLEBOLETA

DECLARE @FechaVencimiento VARCHAR(8)
DECLARE @FechaHoy VARCHAR(8)

SET @FechaHoy = GetDate()
SET @FechaVencimiento = dateadd(dd, 1, @FechaHoy)

UPDATE BOLETA
SET Importe = @ImporteBoleta,
	FechaVencimiento = @FechaVencimiento
WHERE IdBoleta = (
		SELECT IDENT_CURRENT('BOLETA')
		)