CREATE
	OR

ALTER PROCEDURE [dbo].[BORRADO_BOLETAS]
AS
-- DECLARACIÓN DE VARIABLES DE TRABAJO
DECLARE @IdBoleta INT,
	@FechaVencimiento DATE,
	@FechaHoy DATE
DECLARE @contador INT = 0

SET @FechaHoy = GetDate()

-- DECLARACIÓN DEL CURSOR
DECLARE MI_CURSOR CURSOR
FOR
SELECT B.IdBoleta AS IdBoleta,
	B.FechaVencimiento AS FechaVencimiento
FROM BOLETA B
WHERE B.FechaVencimiento < @FechaHoy
	AND B.Estado = 0

-- APERTURA DEL CURSOR
OPEN MI_CURSOR

-- LECTURA DEL PRIMER REGISTRO
FETCH NEXT
FROM MI_CURSOR
INTO @IdBoleta,
	@FechaVencimiento;

-- RECORRER EL CURSOS MIENTRAS HAYAN REGISTROS
WHILE @@FETCH_STATUS = 0
BEGIN
	UPDATE BOLETA
	SET BHabilitado = 0
	WHERE IdBoleta = @IdBoleta

	-- DECLARACIÓN DEL CURSOR DE LOS DETALLES
	DECLARE @IdDetalleBoleta INT = 0

	DECLARE MI_CURSOR_DETALLES CURSOR
	FOR
	SELECT D.IdDetalleBoleta AS IdDetalleBoleta
	FROM DETALLEBOLETA D
	WHERE D.IdBoleta = @IdBoleta

	OPEN MI_CURSOR_DETALLES

	FETCH NEXT
	FROM MI_CURSOR_DETALLES
	INTO @IdDetalleBoleta;

	WHILE @@FETCH_STATUS = 0
	BEGIN
		UPDATE DETALLEBOLETA
		SET BHabilitado = 0
		WHERE IdDetalleBoleta = @IdDetalleBoleta

		FETCH NEXT
		FROM MI_CURSOR_DETALLES
		INTO @IdDetalleBoleta;
	END

	CLOSE MI_CURSOR_DETALLES

	-- LIBERAR EL RECURSO
	DEALLOCATE MI_CURSOR_DETALLES;

	-- FIN CURSOR DE DETALLES
	SET @contador = + 1

	FETCH NEXT
	FROM MI_CURSOR
	INTO @IdBoleta,
		@FechaVencimiento;
END

IF (@contador > 0)
	INSERT INTO CONTROL_PROCESOS (IdProceso)
	VALUES (3);

CLOSE MI_CURSOR

-- LIBERAR EL RECURSO
DEALLOCATE MI_CURSOR;